import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://safawalamumbai.com'
  
  // All Mumbai service pages
  const servicePages = [
    'andheri-safa-service',
    'baarat-safa-in-mumbai',
    'bandhej-safa-in-mumbai',
    'bandra-safa-service',
    'barati-safa-in-mumbai',
    'barati-safa-tying-for-international-wedding',
    'beach-wedding-safa-in-mumbai',
    'black-safa-in-mumbai',
    'blue-safa-in-mumbai',
    'borivali-safa-service',
    'brocade-safa-in-mumbai',
    'brother-of-groom-safa-in-mumbai',
    'buy-safa-in-mumbai',
    'chembur-safa-service',
    'corporate-event-safa-in-mumbai',
    'corporate-event-turban-in-mumbai',
    'cotton-safa-in-mumbai',
    'cream-safa-in-mumbai',
    'custom-wedding-turban-for-overseas-weddings',
    'dadar-safa-service',
    'designer-safa-in-mumbai',
    'designer-wedding-turban',
    'destination-wedding-safa-in-mumbai',
    'destination-wedding-turban',
    'diwali-turban-in-mumbai',
    'dulha-safa-in-mumbai',
    'embroidered-safa-in-mumbai',
    'engagement-safa-in-mumbai',
    'family-safa-service-in-mumbai',
    'father-of-groom-turban-in-mumbai',
    'festival-safa-in-mumbai',
    'feta-in-mumbai',
    'foreigner-turban-experience-in-mumbai',
    'ghatkopar-safa-service',
    'golden-safa-in-mumbai',
    'goregaon-safa-service',
    'gota-patti-safa-in-mumbai',
    'green-safa-in-mumbai',
    'groom-safa-in-mumbai',
    'groom-turban-in-mumbai',
    'group-safa-service-in-mumbai',
    'guest-turban-service-in-mumbai',
    'gujarati-safa-in-mumbai',
    'haldi-safa-in-mumbai',
    'hand-tied-turban-for-international-wedding',
    'holi-turban-in-mumbai',
    'jodhpuri-matching-safa-in-mumbai',
    'jodhpuri-safa-in-mumbai',
    'juhu-safa-service',
    'kalyan-dombivli-safa-service',
    'kandivali-safa-service',
    'khar-safa-service',
    'kharghar-safa-service',
    'kurla-safa-service',
    'kurta-matching-safa-in-mumbai',
    'ladkewale-safa-in-mumbai',
    'ladkiwale-safa-in-mumbai',
    'leheriya-safa-in-mumbai',
    'luxury-wedding-turban-for-groom',
    'malad-safa-service',
    'marathi-pheta-in-mumbai',
    'maroon-safa-in-mumbai',
    'marwari-safa-in-mumbai',
    'mehendi-safa-in-mumbai',
    'mehndi-function-safa-in-mumbai',
    'modern-safa-in-mumbai',
    'mulund-safa-service',
    'mumbai-airport-turban-service',
    'mundan-ceremony-turban-in-mumbai',
    'navi-mumbai-safa-service',
    'navratri-turban-in-mumbai',
    'nerul-safa-service',
    'nri-wedding-safa-in-mumbai',
    'orange-safa-in-mumbai',
    'pagadi-in-mumbai',
    'pagdi-bandhai-in-mumbai',
    'pagdi-for-groom-in-mumbai',
    'pagdi-for-wedding-in-mumbai',
    'pagdi-in-mumbai',
    'pagdi-rental-in-mumbai',
    'pagdi-wala-in-mumbai',
    'paghdi-in-mumbai',
    'pagri-in-mumbai',
    'panvel-safa-service',
    'parel-safa-service',
    'peach-safa-in-mumbai',
    'phera-ceremony-turban-in-mumbai',
    'pheta-tying-in-mumbai',
    'photo-shoot-safa-in-mumbai',
    'pink-safa-in-mumbai',
    'powai-safa-service',
    'premium-wedding-safa-for-international-groom',
    'punjabi-safa-in-mumbai',
    'purple-safa-in-mumbai',
    'rajasthani-safa-in-mumbai',
    'reception-safa-in-mumbai',
    'red-safa-in-mumbai',
    'royal-groom-turban-for-destination-wedding',
    'royal-wedding-turban-in-mumbai',
    'safa-bandhai-in-mumbai',
    'safa-for-groom-in-mumbai',
    'safa-in-mumbai',
    'safa-on-rent-in-mumbai',
    'safa-pagdi-in-mumbai',
    'safa-price-in-mumbai',
    'safa-shop-in-mumbai',
    'safa-shop-near-me-in-mumbai',
    'safa-tying-service-in-mumbai',
    'safa-wala-in-mumbai',
    'same-day-safa-service-in-mumbai',
    'sangeet-safa-in-mumbai',
    'santacruz-safa-service',
    'satin-safa-in-mumbai',
    'sehra-in-mumbai',
    'sehra-safa-in-mumbai',
    'sherwani-matching-safa-in-mumbai',
    'sikh-turban-in-mumbai',
    'silk-safa-in-mumbai',
    'silver-safa-in-mumbai',
    'sindhi-safa-in-mumbai',
    'south-mumbai-safa-service',
    'thane-safa-service',
    'tilak-ceremony-safa-in-mumbai',
    'traditional-indian-wedding-turban-for-groom',
    'traditional-safa-in-mumbai',
    'turban-for-groom-in-mumbai',
    'turban-in-mumbai',
    'turban-rental-near-me-in-mumbai',
    'turban-tying-service-in-mumbai',
    'uncle-turban-in-mumbai',
    'vashi-safa-service',
    'velvet-safa-in-mumbai',
    'vidai-turban-service-in-mumbai',
    'vile-parle-safa-service',
    'wedding-pagdi-for-destination-wedding',
    'wedding-pagdi-in-mumbai',
    'wedding-safa-in-mumbai',
    'wedding-safa-tying-in-mumbai',
    'white-safa-in-mumbai',
    'worli-safa-service',
  ]

  // Static pages
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
  ]

  // Service pages sitemap
  const servicePagesSitemap: MetadataRoute.Sitemap = servicePages.map((page) => ({
    url: `${baseUrl}/${page}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }))

  return [...staticPages, ...servicePagesSitemap]
}
